spring:
  ai:
    alibaba:
      toolcalling:
        baidutranslate:
          enabled: true
          app-id: ${BAIDU_TRANSLATE_APP_ID}
          secret-key: ${BAIDU_TRANSLATE_SECRET_KEY}

        time:
          enabled: true

        weather:
          enabled: true
          api-key: ${WEATHER_API_KEY}

        larksuite:
          enabled: true
          appId: ${LARK_SUITE_APP_ID}
          appSecret: ${LARK_SUITE_APP_SECRET}

    dashscope:
      api-key:  ${AI_DASHSCOPE_API_KEY}

